using System; using System.Collections; using System.Collections.Generic; using UnityEngine;  public class EnemyInfo : CharacterInfo {     /// <summary>     /// Список мертвых врагов.     /// В списке мертвых врагов хораняться еще или уже не задействованые враги.     /// Таким образом на их создание и уничтожение не тратиться время.     /// </summary>     public System.Collections.Generic.List<GameObject> deadEnemy =null;     /// <summary>     /// Список живых врагов.     /// </summary>     public System.Collections.Generic.List<GameObject> aliveEnemy = null;     /// <summary>     /// Объект игрока.     /// </summary>     public GameObject player = null;     /// <summary>     /// Объект с доп. инормацией об игроке.     /// </summary>     private PlayerInfo playerInfo = null;     private GameObject camera = null;     private Single timerAtack = 0;     // Start is called before the first frame update     void Start()     {         this.playerInfo = player.GetComponent<PlayerInfo>();         this.camera = GameObject.Find("Main Camera");     }      // Update is called once per frame     void Update()     {         if (!this.isDead)         {             this.timerAtack += Time.deltaTime;             Vector3 thisPosition = this.transform.position;             Vector3 playerPosition = this.player.transform.position;             if (Math.Abs(thisPosition.x - playerPosition.x) + Math.Abs(thisPosition.y - playerPosition.y) > 2)
            {
                this.transform.position = Vector3.MoveTowards(this.transform.position, this.player.transform.position, 0.008f);
            }
            else
            {
                if (this.timerAtack > 1)
                {
                    this.playerInfo.healthPoints -= this.damage;
                    this.timerAtack = 0;
                }
            }
            this.transform.LookAt(new Vector3                 (                 this.camera.transform.position.x,                  1,                  this.camera.transform.position.z                  ));         }     }      public void OnTriggerEnter(Collider other)     {         Debug.Log(other.gameObject.name);         if (other.gameObject.name == "Bullet(Clone)")         {             Destroy(other.gameObject);             this.healthPoints -= this.playerInfo.damage;              if (this.healthPoints == 0)             {                 this.isDead = true;                 this.aliveEnemy.Remove(this.gameObject);                 this.deadEnemy.Add(this.gameObject);                 this.gameObject.transform.position = new Vector3(this.gameObject.transform.position.x, -99, this.gameObject.transform.position.y);             }         }     } } 